version: "3"
services:
  redis-server:
    container_name: "redis-server"
    image: "redis"
    command: ["redis-server", "--appendonly", "yes"]
  node-app:
    container_name: "node-app"
    build: .
    image: node-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis-server
    environment:
      REDIS_HOST: redis-server
